<?php

use App\CompanyHistory;
use App\Models\Company;
use App\Models\Donor;
use App\Models\ParsedCompany;
use App\Models\Review;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class CompaniesTableSeeder extends Seeder
{
    /**
     * @var Collection|Donor[]
     */
    public $donors = [];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->createDefaultSettings();

        $this->donors = $this->createDonors();

    }

    /**
     * @param Company[]|ParsedCompany[] $companies
     *
     */
    public function makeReviewsForCompanies($companies)
    {

        foreach ($companies as $company) {
            $reviews = factory(Review::class, rand(0, 10))->make();
            $this->associateReviewsWithCompany($reviews, $company);
        }
    }

    /**
     * @param string $name
     * @param null $num
     * @return Collection|ParsedCompany[]
     */
    public function makeParsedCompanies($name = 'default', $num = null)
    {
        return factory(ParsedCompany::class, $name, $num)->make()
            ->each(function (ParsedCompany $parsedCompany) {
                $donor                     = $this->donors->random();
                $parsedCompany->donor_page = $this->generatePivotSite($donor, $parsedCompany);
                $parsedCompany->donor_id   = $donor->id;
            });
    }

    /**
     * @param Collection $collection
     * @param $min
     * @param $max
     * @return array|mixed|static
     */
    function takeRandom(Collection $collection, $min, $max)
    {
        $count = $collection->count();
        if ($max > $count) {
            $max = $count;
            if ($count < $min) {
                [];
            }
        }
        return $collection->random(rand($min, $max));
    }

    /**
     * @param Donor $donor
     * @param ParsedCompany|Company $company
     * @return string
     */
    function generatePivotSite(Donor $donor, $company)
    {
        return $donor->link . '/' . str_slug($company->title);
    }

    /**
     * @param Collection|Review[] $reviews
     * @param ParsedCompany|Company $company
     */
    function associateReviewsWithCompany($reviews, $company)
    {
        $donor = $this->donors->random();
        $company->reviews()->saveMany($reviews);
        foreach ($reviews as $review) {

            $review->donor_link = $this->generatePivotSite($donor, $company);
            $review->donor()->associate($donor);
            $review->save();
        }
    }

    /**
     * @param \Illuminate\Database\Eloquent\Model[] $models
     * @return array
     */
    public function saveMany($models)
    {
        foreach ($models as $model) {
            $model->save();
        }
        return $models;
    }

    public function createCompanyHistory()
    {
        $history = [
            [
                'field'             => 'title',
                'old_value'         => 'test',
                'new_value'         => 'test2',
                'parsed_company_id' => 1,
            ],
        ];
        foreach ($history as $item) {
            CompanyHistory::create($item);
        }
    }

    public function createDefaultSettings()
    {
        setting()->setSetting('time', 4);
        setting()->setSetting('proxies', '127.0.0.1:8080');
        setting()->setSetting('concurrency', '2');
    }

    public function createDonors()
    {
        $donors = collect([
            [
                'link'         => 'https://avtosalon-otzyv.ru/',
                'title'        => 'Автосалон отзыв',
                'mass_parsing' => true,

                'loop_address'        => '.entry-summary p:last-child',
                'loop_item'           => 'main article',
                'loop_link'           => '.read-more a',
                'loop_title'          => 'h3',
                'replace_search'      => '</header><!-- .entry-header -->',
                'replace_to'          => '</div></header><!-- .entry-header -->',
                'reviews_all'         => 'main .full-testimonial',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '.stars',
                'reviews_text'        => '.rr_review_text',
                'reviews_title'       => 'h3',
                'reviews_name'        => '.rr_review_name span',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => 'noindex',
                'single_address'      => '#view1 + p',
                'single_tel'          => '',
                'single_title'        => 'h2.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://otziv-avto.ru/',
                'title'               => 'Отзыв авто',
                'mass_parsing'        => true,
                'loop_address'        => '.su-post-excerpt',
                'loop_item'           => '.su-post',
                'loop_link'           => 'h2 a',
                'loop_links'         => '#menu-main a',
                'loop_title'          => 'h2',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.comment-body',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '.stars',
                'reviews_text'        => '.comment-content',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => './*/@id',
                'single_site'         => '//div[@id="primary"]//*/text()[contains(.,"Сайт")]/..',
                'single_address'      => '//div[@id="primary"]//*/text()[contains(.,"Адрес")]',
                'single_tel'          => '//div[@id="primary"]//*/text()[contains(.,"Тел")]',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.menu-item-102 a',
            ],
            [
                'link'                => 'http://rater.club/',
                'title'               => 'Rater Club',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.uk-article',
                'loop_link'           => 'h1 a',
                'loop_title'          => 'h1',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.rbox',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-body',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '//*[@class="comment-anchor"]/@id',
                'single_site'         => '//tr//*/text()[contains(.,"Сайт")]/../..',
                'single_address'      => '//tr//*/text()[contains(.,"Адрес")]/../..',
                'single_tel'          => '//tr//*/text()[contains(.,"Телефон")]/../..',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.uk-pagination li a',
            ],
            [
                'link'                => 'http://mail-auto.ru/',
                'title'               => 'Mail Auto',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => 'tbody tr',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.rbox',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-body',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '//*[@class="comment-anchor"]/@id',
                'single_site'         => '//article[@class="uk-article"]//p/text()[contains(.,"Сайт")]/..',
                'single_address'      => '//article[@class="uk-article"]//p/text()[contains(.,"Адрес")]',
                'single_tel'          => '//article[@class="uk-article"]//p/text()[contains(.,"Телефон")]',
                'single_title'        => 'h1.uk-article-title',
                'single_city'         => '',
                'archive_pagination'  => 'form .uk-pagination a, .uk-nav.uk-nav-navbar a',
            ],
            [
                'link'                => 'http://xn----7sbgzkqfjydk.xn--p1ai/avtosalony',
                'title'               => 'авто-путник',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.listing-summary',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.review-text',
                'reviews_title'       => '.review-title',
                'reviews_name'        => '.review-owner',
                'reviews_id'          => '//div[@class="review-title"]/a/@id',
                'single_site'         => '',
                'single_address'      => '//div[@id="listing"]//div/text()[contains(.,"Адрес")]/..',
                'single_tel'          => '//div[@id="listing"]//div/text()[contains(.,"Телефон")]/..',
                'single_title'        => 'h2',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'http://mnenieavto.ru',
                'title'               => 'Мнение авто',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.the_comment_text',
                'reviews_title'       => '',
                'reviews_name'        => '.the_comment_author',
                'reviews_id'          => '//div[@class="review-title"]/a/@id',
                'single_site'         => '.entry-content',
                'single_address'      => '',
                'single_tel'          => '.entry-content',
                'single_title'        => '.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.navigation a',
            ],
            [
                'link'                => 'https://auto-review.info/avtosalon',
                'title'               => 'Auto review',
                'mass_parsing'        => true,
                'loop_links'          => '#menu-main a',
                'loop_address'        => '',
                'loop_item'           => '.su-post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-content',
                'reviews_title'       => '.head_com',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.entry',
                'single_address'      => '.entry',
                's_address_regex'     => '/Адрес\s?.*/i',
                'single_tel'          => '.entry',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '#menu-item-102 a',
            ],
            [
                'link'                => 'https://avtosalon-review.ru/',
                'title'               => 'avtosalon-review',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h1 a',
                'loop_title'          => 'h1',
                'replace_search'      => '</header><!-- .entry-header -->',
                'replace_to'          => '</div></header><!-- .entry-header -->',
                'reviews_all'         => '.full-testimonial',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.rr_review_text',
                'reviews_title'       => '.rr_title',
                'reviews_name'        => '.rr_review_name span',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//h3/text()[contains(.,"Вебсайт")]/../following-sibling::noindex/a',
                'single_address'      => '//h3/text()[contains(.,"Адрес")]/../following-sibling::p',
                'single_tel'          => '',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.k2Pagination a',
            ],
            [
                'link'                => 'https://kritika.su/otzyvy/auto/avtosalony.html',
                'title'               => 'kritika.su',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.listing-summary',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.review-text',
                'reviews_title'       => '.review-title',
                'reviews_name'        => '.review-owner',
                'reviews_id'          => '',
                'reviews_pagination'  => '.pagination a',
                'single_site'         => '//div[@id="listing"]//div[@class="caption"]/text()[contains(.,"Сайт")]/../..//a',
                'single_address'      => '//div[@id="listing"]//div[@class="caption"]/text()[contains(.,"Адрес")]/../..',
                'single_tel'          => '//div[@id="listing"]//div[@class="caption"]/text()[contains(.,"Телефон")]/../..',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'http://rtdm-auto.ru/',
                'title'               => 'rtdm-auto',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '.review-title',
                'reviews_name'        => 'cite',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="entry-content"]//li[contains(.,"Сайт")]',
                'single_address'      => '//div[@class="entry-content"]//li[contains(.,"Адрес")]',
                'single_tel'          => '//div[@class="entry-content"]//li[contains(.,"Телефон")]',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '#main-navigation li:nth-child(2) a,#main-navigation li:nth-child(3) a,#main-navigation li:nth-child(4) a,#main-navigation li:nth-child(7) a, #post-navigator a',
            ],
            [
                'link'                => 'https://trueslns.ru/?limitstart=0',
                'title'               => 'trueslns',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.listing-summary',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.review-text',
                'reviews_title'       => '',
                'reviews_name'        => '.review-owner',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="fields"]//div[@class="caption"]/text()[contains(.,"Сайт")]/../../..',
                'single_address'      => '//div[@class="fields"]//div[@class="caption"]/text()[contains(.,"Адрес")]/../..',
                'single_tel'          => '//div[@class="fields"]//div[@class="caption"]/text()[contains(.,"Телефон")]/../..',
                'single_title'        => 'h2',
                'single_city'         => '',
                'archive_pagination'  => '.pages-links a',
            ],
            [
                'link'                => 'https://xn----dtbas7abcdze4h.xn--p1ai/katalog-avtosalonov/',
                'title'               => 'топ-отзывов',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.su-post',
                'loop_link'           => 'h2 a',
                'loop_links'          => 'div[class="menu-%d0%bf%d0%be%d0%bf%d1%83%d0%bb%d1%8f%d1%80%d0%bd%d1%8b%d0%b5-container"] a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => 'cite',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="blog-block single-page"]/p/text()[contains(.,"Сайт")]',
                'single_address'      => '//div[@class="blog-block single-page"]/p/text()[contains(.,"Адрес")]',
                'single_tel'          => '//div[@class="blog-block single-page"]/p/text()[contains(.,"Телефон")]',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'http://rusavtodiler.ru',
                'title'               => 'rusavtodiler',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h1 a',
                'loop_title'          => 'h1 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.content-annina .full-testimonial',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.rr_review_text',
                'reviews_title'       => '.rr_title',
                'reviews_name'        => '.rr_review_name',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => 'article a',
                'single_address'      => '',
                'single_tel'          => 'article',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'http://bp-auto.ru/car-showrooms/',
                'title'               => 'bp-auto',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h5 a',
                'loop_title'          => 'h5 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.author-card',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.post pre',
                'single_address'      => '.post pre',
                's_address_regex'     => '/Адрес\s?.*/i',
                'single_tel'          => '.post pre',
                'single_title'        => '.tag_line_title',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'http://dealer-auto.ru/avtosalony/',
                'title'               => 'dealer-auto',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '</br>',
                'replace_to'          => '<br/>',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '.lets-review-ur-headline',
                'reviews_name'        => 'cite',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//section[@class="cb-entry-content clearfix"]/text()[contains(.,\'Сайт\') or contains(.,"Auto.ru")]/following-sibling::a',
                'single_address'      => '//section[@class="cb-entry-content clearfix"]/text()[contains(.,\'Адрес\')]/following-sibling::b',
                'single_tel'          => '//section[@class="cb-entry-content clearfix"]/text()[contains(.,\'✆\')]',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.page-numbers a',
            ],
            [
                'link'                => 'http://bookrates.ru/',
                'title'               => 'Book rates',
                'mass_parsing'        => false,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '</br>',
                'replace_to'          => '<br/>',
                'reviews_all'         => '.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-text',
                'reviews_title'       => '.lets-review-ur-headline',
                'reviews_name'        => '.author',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="center"]//text()[contains(.,"сайт")]/../..',
                'single_address'      => '//div[@class="center"]//text()[. = "Адрес"]/../..',
                'single_tel'          => '//div[@class="center"]//text()[contains(.,"Телефон")]/../..',
                'single_title'        => 'h1',
                'single_city'         => '//div[@class="center"]//text()[contains(.,"Город")]/../..',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://top-otziv.ru/spisok-salonov/',
                'title'               => 'Top-otziv',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.su-post',
                'loop_link'           => 'h2 a',
                'loop_links'          => '#recent-posts-6 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-content',
                'reviews_title'       => '.lets-review-ur-headline',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="entry-content clearfix"]//text()[contains(.,"Сайт")]',
                'single_address'      => '//div[@class="entry-content clearfix"]//text()[contains(.,"Адрес")]',
                'single_tel'          => '//div[@class="entry-content clearfix"]//text()[contains(.,"Тел.") or contains(.,"Телефон")]',
                'single_title'        => '.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://avtospletnik.com/carshowroom/',
                'title'               => 'https://avtospletnik.com/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post-card',
                'loop_link'           => '.entry-title a',
                'loop_title'          => '.entry-title a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-text',
                'reviews_title'       => '.lets-review-ur-headline',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="taxonomy_left"]//text()[contains(.,"Сайт")]/..',
                'single_address'      => '//div[@class="taxonomy_left"]//text()[contains(.,"Адрес")]/..',
                'single_tel'          => '//div[@class="taxonomy_left"]//text()[contains(.,"Телефон")]/..',
                'single_title'        => '.entry-title',
                'single_city'         => '//div[@class="taxonomy_left"]//text()[contains(.,"Город")]/..',
                'archive_pagination'  => '.spoiler-box__body > a,.nav-links a',
            ],
            [
                'link'                => 'http://xn----7sbbaabk7edlfchc6bo.xn--p1ai/',
                'title'               => 'http://обман-автосалона.рф',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-content',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="entry-content"]//text()[contains(.,"Сайт")]/ancestor::p',
                'single_address'      => '//div[@class="entry-content"]//text()[contains(.,"Адрес")]/ancestor::p',
                'single_tel'          => '//div[@class="entry-content"]//text()[contains(.,"Телефон")]/ancestor::p',
                'single_title'        => '.entry-title',
                'single_city'         => '//div[@class="entry-content"]//text()[contains(.,"Город")]/ancestor::p',
                'archive_pagination'  => '.nav-links a',
            ],
            [
                'link'                => 'https://acauto.su/avtosalony-moskvy',
                'title'               => 'acauto.su',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.vcard',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="entry-content clearfix"]//text()[contains(.,"Сайт")]/ancestor::li[1]',
                'single_address'      => '//div[@class="entry-content clearfix"]//text()[contains(.,"Адрес")]/ancestor::li[1]',
                'single_tel'          => '//div[@class="entry-content clearfix"]//text()[contains(.,"Телефон")]/ancestor::li[1]',
                'single_title'        => '.entry-title',
                'single_city'         => '//div[@class="entry-content clearfix"]//text()[contains(.,"Город")]/ancestor::li[1]',
                'archive_pagination'  => '.pagination a,#menu-menu-1 li:nth-child(2) a',
            ],
            [
                'link'                => 'http://xn--b1ajeind2a7e.xn--p1ai/10-otzyvy-ob-avtosalone?limitstart=0',
                'title'               => 'отзывник.рф',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '*[itemprop="blogPost"]',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => '',
                'reviews_all'         => '.rbox',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-body',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@itemprop="articleBody"]//text()[contains(.,"Сайт")]/ancestor::p[1]',
                'single_address'      => '//div[@itemprop="articleBody"]//text()[contains(.,"Адрес")]/ancestor::p[1]',
                'single_tel'          => '//div[@itemprop="articleBody"]//text()[contains(.,"Телефон")]/ancestor::p[1]',
                'single_title'        => '.page-header h2',
                'single_city'         => '//div[@itemprop="articleBody"]//text()[contains(.,"Город")]/ancestor::p[1]',
                'archive_pagination'  => '.pagination a,#menu-menu-1 li:nth-child(2) a',
            ],
            [
                'link'                => 'https://cenamashin.ru/autosalon',
                'title'               => 'https://cenamashin.ru',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.mycol[style="height: 60px;"]',
                'loop_link'           => 'a[style=""]',
                'loop_title'          => 'a[style=""]',
                'replace_search'      => '<br>',
                'replace_to'          => "\r\n<br>",
                'reviews_all'         => 'table[width="99%"]',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'div[id]',
                'reviews_title'       => '',
                'reviews_name'        => 'a[title="Ссылка на отзыв"]',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="data-block" and contains(.,"Просмотров")]',
                'single_address'      => 'font:nth-child(4)',
                'single_tel'          => '//div[@class="data-block" and contains(.,"Просмотров")]',
                'single_title'        => 'h1',
                'single_city'         => 'font:nth-child(2)',
                'archive_pagination'  => '.data-block a[href*="page"],.data-block a[style="font-weight: bold;"]',
            ],
            [
                'link'                => 'https://salon-otziv.ru',
                'title'               => 'https://salon-otziv.ru',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => 'h4',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//tr[contains(.//img/@src,"site")]/td[2]',
                'single_address'      => '//tr[contains(.//img/@src,"location")]/td[2]',
                'single_tel'          => '//tr[contains(.//img/@src,"phone")]/td[2]',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.archive-nav a',
            ],
            [
                'link'                => 'http://autosalon1.ru/',
                'title'               => 'http://autosalon1.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '</br>',
                'replace_to'          => "\r\n<br/>",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.salon-info',
                'single_address'      => '//div[@class="salon-info"]//text()[contains(.,"Адрес")]/following-sibling::text()[1]',
                'single_tel'          => '.salon-info',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.post-navigation a',
            ],
            [
                'link'                => 'http://xn--80ab4af2a6c0a.xn--p1ai/',
                'title'               => 'http://ябылтам.рф',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '<br />',
                'replace_to'          => "\r\n<br />",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="entry-content"]//text()[contains(.,"Сайт")]/following-sibling::*[1]',
                'single_address'      => '//div[@class="entry-content"]//text()[contains(.,"Адрес")]/following-sibling::*[1]',
                'single_tel'          => '.entry-content',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.nav-links a',
            ],
            [
                'link'                => 'https://ratingsalon.ru/',
                'title'               => 'https://ratingsalon.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.main-navigation li',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '<br />',
                'replace_to'          => "\r\n<br />",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//tr[contains(.,"Сайт")]/td[2]',
                'single_address'      => '//tr[contains(.,"адрес")]/td[2]',
                'single_tel'          => '.contact-address,.entry-content',
                'single_title'        => 'h1.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '.nav-links a',
            ],
            [
                'link'                => 'http://otzivosalone.ru/page/1/',
                'title'               => 'http://otzivosalone.ru',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.listing-tube li',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '//header/text()[2]',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//tr[contains(.//img/@src,"link")]/td[2]',
                'single_address'      => '//tr[contains(.//img/@src,"mestopolojnie")]/td[2]',
                'single_tel'          => '//tr[contains(.//img/@src,"telefon")]/td[2]',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'http://gdemnenie.ru/',
                'title'               => 'http://gdemnenie.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.entry-content li',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.entry-content',
                'single_address'      => '//div[@class="entry-content"]//strong[contains(.,"Адрес")]/following-sibling::text()[1]',
                'single_tel'          => '.entry-content',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'https://auto-otzovik.ru/',
                'title'               => 'https://auto-otzovik.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.su-post',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.entry-content',
                'single_address'      => '//div[@class="entry-content"]//text()[contains(.,"Адрес")]',
                'single_tel'          => '.entry-content',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '#menu-item-102 a',
            ],
            [
                'link'                => 'http://mnenie-avto.ru/blog/',
                'title'               => 'http://mnenie-avto.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.vc_grid-item',
                'loop_link'           => 'h4 a',
                'loop_title'          => 'h4 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.blog-content p',
                'single_address'      => '//div[@class="blog-content"]//text()[contains(.,"Адрес")]',
                'single_tel'          => '.blog-content p',
                'single_title'        => '.blog-single-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://carrr.club/otzyvy/avtosalony.html',
                'title'               => 'https://carrr.club/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.lsrow',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'span[itemprop="reviewBody"]',
                'reviews_title'       => '.review-title',
                'reviews_name'        => '.review-owner',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//div[@class="row0" and contains(.,"сайт")]//div[@class="output"]',
                'single_address'      => '//div[@class="row0" and contains(.,"адрес")]//div[@class="output"]',
                'single_tel'          => '.fields',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'https://mail.otzyv-ekb.info/avtosalony',
                'title'               => 'https://mail.otzyv-ekb.info',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.itemContainer',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.comments-list > div',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.uk-list',
                'single_address'      => '//li[contains(.//i/@class,"map-marker")][1]',
                'single_tel'          => '.uk-list',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'https://otzyv-ekb.com/avtosalony',
                'title'               => 'https://otzyv-ekb.com/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.itemContainer',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.comments-list > div',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.uk-list',
                'single_address'      => '//li[contains(.//i/@class,"map-marker")][1]',
                'single_tel'          => '.uk-list',
                'single_title'        => 'h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'http://otzyv.zone/town/avtosalony',
                'title'               => 'http://otzyv.zone/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.itemContainer',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.reviewBlock, .jreview-comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '//div[@itemprop="reviewBody"] | ./*/div/div[@class="_comment"]',
                'reviews_title'       => 'h3',
                'reviews_name'        => './*/div/div/a | ./*/div/div/span[@class="_author"]',
                'reviews_id'          => '',
                'reviews_pagination'  => '.jreview-pagination a',
                'single_site'         => '.itemExtraFields',
                'single_address'      => '//div[@class="itemExtraFields"]//li[contains(.,"адрес")]/span[2]',
                'single_tel'          => '.itemExtraFields',
                'single_title'        => 'h1',
                'single_city'         => '//div[@class="itemExtraFields"]//li[contains(.,"город")]/span[2]',
                'archive_pagination'  => '.k2Pagination a',
            ],
            [
                'link'                => 'http://carscorp.ru/component/option,com_mtree/Itemid,10/cat_id,57/task,listcats/',
                'title'               => 'http://carscorp.ru/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.listing-summary',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.review-text',
                'reviews_title'       => '.review-title',
                'reviews_name'        => '.review-owner',
                'reviews_id'          => '',
                'reviews_pagination'  => '.pagination a',
                'single_site'         => '',
                'single_address'      => '//div[@class="row" and contains(.,"Адрес")]/div[2]',
                'single_tel'          => '.fields',
                'single_title'        => 'h1',
                'single_city'         => '//div[@class="row" and contains(.,"Город")]/div[2]',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'https://autosalon-rating.ru',
                'title'               => 'https://autosalon-rating.ru',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.automarkets-aside-list li',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.commentBlock',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.message',
                'reviews_title'       => '',
                'reviews_name'        => '.name',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.data-rows',
                'single_address'      => '//div[@class="data-item" and contains(.//i/@class,"fa-map-marker")]/div[2]',
                'single_tel'          => '.data-rows',
                'single_title'        => 'div h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination a',
            ],
            [
                'link'                => 'https://papasalon.com/otzyvy/avtosalony',
                'title'               => 'https://papasalon.com',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.itemContainer',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.reviewBlock, .jreview-comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '//div[@itemprop="reviewBody"] | ./*/div/div[@class="_comment"]',
                'reviews_title'       => 'h3',
                'reviews_name'        => './*/div/div/a | ./*/div/div/span[@class="_author"]',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.itemExtraFields',
                'single_address'      => '//div[@class="itemExtraFields k2-row"]//li[contains(.,"адрес")]/span[2]',
                'single_tel'          => '.itemExtraFields',
                'single_title'        => 'h1',
                'single_city'         => '//div[@class="itemExtraFields k2-row"]//li[contains(.,"город")]/span[2]',
                'archive_pagination'  => '.k2Pagination a',
            ],
            [
                'link'                => 'https://carsguru.net/company/salon',
                'title'               => 'https://carsguru.net/',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.dealers-list__item',
                'loop_link'           => '.elem__link a',
                'loop_title'          => '.elem__link a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.opinions .item',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => '',
                'reviews_name'        => '.author-lnk',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '//a[@class="carsguru-dynamick-link"]/@data-content',
                'single_address'      => '.main-item address',
                'single_tel'          => 'dl',
                'single_title'        => '.main-heading h1',
                'single_city'         => '',
                'archive_pagination'  => '.pager a',
                'decode_url'          => true,
            ],
            [
                'link'                => 'http://autoneva.ru/avtosalony/search/',
                'title'               => 'autoneva.ru',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.result_item',
                'loop_link'           => '.name a',
                'loop_title'          => '.name a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.review',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.content',
                'reviews_title'       => '.name',
                'reviews_name'        => '.author a',
                'reviews_id'          => '',
                'reviews_pagination'  => '.page_navi a',
                'single_site'         => '.addr',
                'single_address'      => '//div[@class="adr" and contains(.,"Адрес")]//p[2]',
                's_address_regex'     => '',
                'single_tel'          => '.addr',
                'single_title'        => '.title.br',
                'single_city'         => '',
                'archive_pagination'  => '.page_navi a',
            ],
            [
                'link'                => 'https://edgo.ru/wp-admin/admin-ajax.php',
                'title'               => 'edgo.ru',
                'parser'              => \App\Parsers\EdgoParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.list_view',
                'loop_link'           => 'h4 a',
                'loop_title'          => 'h4 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.review-post',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => '.content-section p:nth-child(2)',
                'reviews_title'       => 'h3',
                'reviews_name'        => 'h4',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.post-detail-content, .list-st-img',
                'single_address'      => '.lp-details-address',
                's_address_regex'     => '',
                'single_tel'          => '.post-detail-content, .list-st-img',
                'single_title'        => '.post-meta-left-box h1',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'http://aool.ru/jm-ajax/get_listings/',
                'title'               => 'http://aool.ru',
                'parser'              => \App\Parsers\AoolParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.grid__item',
                'loop_link'           => 'a',
                'loop_title'          => 'h2',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '... Читать полностью',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => 'h3',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.single-meta',
                'single_address'      => '.listing-address',
                's_address_regex'     => '',
                'single_tel'          => '.single-meta',
                'single_title'        => '.entry-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'http://mosotziv.ru/jm-ajax/get_listings/',
                'title'               => 'http://mosotziv.ru',
                'parser'              => \App\Parsers\MosotzivParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.grid__item',
                'loop_link'           => 'a',
                'loop_title'          => 'h2',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.wpjmr-list-reviews + p',
                'reviews_title'       => '',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => 'main .map-widget-section:nth-child(2), .listify_widget_panel_listing_content',
                'single_address'      => '.listing-address',
                's_address_regex'     => '',
                'single_tel'          => 'main .map-widget-section:nth-child(2), .listify_widget_panel_listing_content',
                'single_title'        => '.job_listing-title',
                'single_city'         => '.content-single-job_listing-hero-inner .job_listing-location',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://otzovik.city/wp-admin/admin-ajax.php',
                'title'               => 'https://otzovik.city',
                'parser'              => \App\Parsers\OtzovikParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.col-xs-12',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => 'h3',
                'reviews_name'        => '.comment__by',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.widget_author__address',
                'single_address'      => '.widget_author__address .map-item',
                's_address_regex'     => '',
                'single_tel'          => '.widget_author__address',
                'single_title'        => '.listing-single__title h1',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'http://mnenie-avto.ru/wp-json/wp/v2/posts',
                'title'               => 'http://mnenie-avto.ru',
                'parser'              => \App\Parsers\MnenieAvtoParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.col-xs-12',
                'loop_link'           => 'h3 a',
                'loop_title'          => 'h3 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => 'li.comment',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'p',
                'reviews_title'       => 'h3',
                'reviews_name'        => '.fn',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.blog-content',
                'single_address'      => '.blog-content',
                's_address_regex'     => '/Адрес\s?.*/i',
                'single_tel'          => '.blog-content',
                'single_title'        => '.blog-single-title',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
            [
                'link'                => 'https://autocensor.com/otzyvy/avtosalony',
                'title'               => 'https://autocensor.com',
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.itemContainer',
                'loop_link'           => 'h2 a',
                'loop_title'          => 'h2 a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.rbox',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => 'div[itemprop="reviewBody"]',
                'reviews_title'       => 'h3',
                'reviews_name'        => '.author-block span[itemprop="name"]',
                'reviews_id'          => '',
                'reviews_pagination'  => '',
                'single_site'         => '.itemExtraFieldsBlock',
                'single_address'      => '//tr[contains(.,"адрес")]/td[2]',
                's_address_regex'     => '',
                'single_tel'          => '.itemExtraFieldsBlock',
                'single_title'        => '.itemTitle',
                'single_city'         => '//tr[contains(.,"город")]/td[2]',
                'archive_pagination'  => '.k2Pagination a',
            ],
            [
                'link'                => 'https://xn----7sbahc3a0aqgcc4ali0lb.xn--p1ai/',
                'title'               => 'автосалон-отзывы.рф',
                'parser'              => \App\Parsers\AvtosalonOtziviRf::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => 'tbody tr',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.rbox',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.comment-body',
                'reviews_title'       => '.comment-title',
                'reviews_name'        => '.comment-author',
                'reviews_id'          => '',
                'reviews_pagination'  => '#nav-top span.page',
                'single_site'         => '',
                'single_address'      => '',
                's_address_regex'     => '',
                'single_tel'          => '',
                'single_title'        => '.page-header h1',
                'single_city'         => '',
                'archive_pagination'  => '.pagination-list a',
            ],
            [
                'link'                => 'http://mnenie-auto.ru/vse-avtosalony/',
                'title'               => 'http://mnenie-auto.ru',
                'parser'              => \App\Parsers\SelectorParser::class,
                'mass_parsing'        => true,
                'loop_address'        => '',
                'loop_item'           => '.category-item',
                'loop_link'           => 'a',
                'loop_title'          => 'a',
                'replace_search'      => '',
                'replace_to'          => "",
                'reviews_all'         => '.masonry-item',
                'reviews_ignore_text' => '',
                'reviews_rating'      => '',
                'reviews_text'        => '.blog-content',
                'reviews_title'       => '',
                'reviews_name'        => 'h5',
                'reviews_id'          => '',
                'reviews_pagination'  => '#nav-top span.page',
                'single_site'         => '.category-description',
                'single_address'      => '',
                's_address_regex'     => '',
                'single_tel'          => '.category-description',
                'single_title'        => '.breadcrumbs-list li:nth-child(2)',
                'single_city'         => '',
                'archive_pagination'  => '',
            ],
        ]);

        foreach ($donors as $donor) {
            $donors[] = Donor::create($donor);
        }
        return $donors;
    }
}


